language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "4.0"
  - "4.1"
before_install:
  # Add repository key
  - "curl -s http://archive.cloudera.com/cdh4/ubuntu/precise/amd64/cdh/archive.key | sudo apt-key add -"
  - "wget http://archive.cloudera.com/cdh4/one-click-install/precise/amd64/cdh4-repository_1.0_all.deb"
  # Add Cloudera repository
  - "sudo dpkg -i cdh4-repository_1.0_all.deb"
  - "sudo apt-get update -qq"
  # Install ZooKeeper
  - "sudo apt-get install -y zookeeper-server"
before_script:
  - "sudo service zookeeper-server init"
  - "sudo service zookeeper-server start"
script: "npm run-script test-ci"
after_script:
  - "sudo service zookeeper-server stop"
  - "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
